///
/// @Generated by Mockolo
///



import Combine
import Foundation
@testable import Connector


public class DataProviderMock: DataProvider {
    public init() { }
    public init(retryPolicy: RetryPolicy? = nil, taskManager: TaskManager) {
        self.retryPolicy = retryPolicy
        self._taskManager = taskManager
    }



    public var retryPolicy: RetryPolicy? = nil

    public var fetchCallCount = 0
    public var fetchArgValues = [any Endpoint]()
    public var fetchHandler: ((any Endpoint) async throws -> Any)?
    public func fetch<T: Decodable>(from endpoint: any Endpoint) async throws -> T {
        fetchCallCount += 1
        fetchArgValues.append(endpoint)
        if let fetchHandler = fetchHandler {
            return try await fetchHandler(endpoint) as! T
        }
        fatalError("fetchHandler returns can't have a default value thus its handler must be set")
    }


    private var _taskManager: TaskManager!
    public var taskManager: TaskManager {
        get { return _taskManager }
        set { _taskManager = newValue }
    }

    public var cancelAllRequestsCallCount = 0
    public var cancelAllRequestsHandler: (() async -> ())?
    public func cancelAllRequests() async {
        cancelAllRequestsCallCount += 1
        if let cancelAllRequestsHandler = cancelAllRequestsHandler {
            await cancelAllRequestsHandler()
        }
        
    }

    public var cancelRequestCallCount = 0
    public var cancelRequestArgValues = [any Endpoint]()
    public var cancelRequestHandler: ((any Endpoint) async -> ())?
    public func cancelRequest(for endpoint: any Endpoint) async {
        cancelRequestCallCount += 1
        cancelRequestArgValues.append(endpoint)
        if let cancelRequestHandler = cancelRequestHandler {
            await cancelRequestHandler(endpoint)
        }
        
    }
}

public class EndpointMock<Response: Decodable>: Endpoint {
    public init() { }
    public init(endpointURL: URL = URL(fileURLWithPath: ""), httpMethod: HTTPMethod? = nil, headers: [String: String]? = nil, parameters: [String: Any]? = nil) {
        self.endpointURL = endpointURL
        self.httpMethod = httpMethod
        self.headers = headers
        self.parameters = parameters
    }



    public var endpointURL: URL = URL(fileURLWithPath: "")


    public var httpMethod: HTTPMethod? = nil


    public var headers: [String: String]? = nil


    public var parameters: [String: Any]? = nil
}

public class ConnectorMock<EndpointType: Endpoint>: Connector {
    public init() { }
    public init(dataProvider: DataProvider = DataProviderMock()) {
        self.dataProvider = dataProvider
    }



    public var dataProvider: DataProvider = DataProviderMock()

    public var fetchCallCount = 0
    public var fetchArgValues = [EndpointType]()
    public var fetchHandler: ((EndpointType) async throws -> EndpointType.Response)?
    public func fetch(from endpoint: EndpointType) async throws -> EndpointType.Response {
        fetchCallCount += 1
        fetchArgValues.append(endpoint)
        if let fetchHandler = fetchHandler {
            return try await fetchHandler(endpoint)
        }
        fatalError("fetchHandler returns can't have a default value thus its handler must be set")
    }
}

public class RetryPolicyMock: RetryPolicy {
    public init() { }
    public init(maxRetryAttempts: Int = 0) {
        self.maxRetryAttempts = maxRetryAttempts
    }



    public var maxRetryAttempts: Int = 0

    public var delayCallCount = 0
    public var delayArgValues = [Int]()
    public var delayHandler: ((Int) -> TimeInterval)?
    public func delay(forAttempt attempt: Int) -> TimeInterval {
        delayCallCount += 1
        delayArgValues.append(attempt)
        if let delayHandler = delayHandler {
            return delayHandler(attempt)
        }
        return 0.0
    }
}



